MySQL:
  host: localhost
  port: 3306
  database: sao_db
  username: root
  password: vertrigo
  table: player_db
PlayerStats:
  maxAgi: 200
  maxHealth: 200
  maxDex: 200
  maxStr: 200
  maxLevel: 200